### PR TITLE
Fix protobuf 3 compatibility issue

### PR DESCRIPTION
**Pull request by cranti**
I've encountered https://github.com/banjiewen/bernhard/issues/29 only on Linux (not OSX), but it seems to be fixed when the name of the generated file ends in "_pb2.py" (checked in [descriptor.cc](https://github.com/google/protobuf/blob/v3.2.0/python/google/protobuf/pyext/descriptor.cc#L95))

### CODE REVIEW

**Comment by cranti** [comment]
Semi-related issues: https://github.com/ethereon/caffe-tensorflow/pull/105 and https://github.com/google/protobuf/issues/2896

**Comment by srikiraju** [comment]
Have the same problem. I tested your fix on my dev envs and it worked. Thanks a lot.

**Comment by srikiraju** [comment]
@banjiewen Any chance we can get a version cut out of this?

**Comment by banjiewen** [comment]
@srikiraju: Yeah, absolutely - should get to it this weekend.

**Comment by banjiewen** [comment]
@cranti: Can you squash this down to one commit?

**Comment by cranti** [comment]
@banjiewen yep, all set

**Comment by srikiraju** [comment]
@banjiewen Bump :)

**Comment by banjiewen** [comment]
Thanks! I've cut `0.2.5` and pushed it to pypi.

**Pull request merged**
