### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by msabramo**
Syntax highlight. See https://github.com/msabramo/bernhard/blob/patch-1/README.md

### CODE REVIEW

**Comment by banjiewen** [comment]
Huh, I've never used `~~~` before, and it's not documented in the [GHFM](https://help.github.com/articles/github-flavored-markdown/) docs, though the backtick-based identifier is. Is there a reason to prefer the tildes?

**Comment by msabramo** [comment]
Yeah I don't know why it's not documented. I learned about it recently by seeing it used elsewhere. I use it because it's easier to type on an iPhone.

**Comment by banjiewen** [comment]
Cool, I committed the same fix with backticks.

**Comment by msabramo** [comment]
Cool!

**Pull request closed without merging**
