### PR TITLE
support sending multiple events

### PR DESCRIPTION
**Pull request by zackdever**
another take on https://github.com/banjiewen/bernhard/pull/9

### CODE REVIEW

**Comment by banjiewen** [comment]
:rocket:

**Comment by zackdever** [comment]
So fast, thanks! Any thought on when the next pypi release will be?

**Comment by banjiewen** [comment]
Already cut: https://pypi.python.org/pypi/bernhard/0.2.4

**Comment by zackdever** [comment]
Much appreciated.

**Pull request merged**
